### ISSUE TITLE
CPANSA-urxvt-bgdsl is a darkpan application, should this be moved to external_reports

### ISSUE THREAD

**Issue by stigtsp** [briandfoy/cpan-security-advisory#124]
Cc @garu

**Comment by briandfoy** [comment]
No. If it's in @INC, we don't care where it came from.

External reports are for non-perl things that perl modules use. It's a different setup.

**Comment by garu** [comment]
Hey brian!

urxvt is a standalone app that has nothing to do with CPAN, it just happens to be written in Perl. It is hosted in http://software.schmorp.de/pkg/rxvt-unicode.html.

To the best of our knowledge, urxvt-bgdsl is not nor has ever been on CPAN. Maybe they also don't belong in 'external_reports' (assuming those are for libraries used by CPAN modules) but does it make sense to have a CPAN Security Advisory entry for projects that have never been on CPAN?

**Comment by briandfoy** [comment]
For now, it makes sense. More data is good for now, even if we don't use it. At the moment, we don't need to do a bunch of work to distinguish these then change all the tools to support that.

**Comment by garu** [comment]
In that case I'll file a PR in a few minutes to work around an issue that happens on cpan-audit whenever it queries metacpan for a distribution that was never there.

**Comment by garu** [comment]
Ok, so there is a problem with keeping them under cpansa. When generating DB.pm, the key is the "distribution" field, but that simply can't be the current name because it isn't on CPAN and thus if someone ever uploads a CPAN dist with that name then DB.pm will be populated with weird versions that won't map to the external app's versions, making people believe their version is safe/dangerous when it's not.

Also, if anyone uploads a dist to CPAN with the name that is on the 'distribution' field and that dist contains a vulnerability that eventually gets assigned a CPANSA id, what will it be? And what will the 'distribution' value say?

The solution is either:
  1. coming up with a new structure;
  2. renaming the 'distribution' field of all non-CPAN entries;
  3. make 'distribution' undef for non-CPAN entries and skipping then when generating DB.pm.
 
Option "3" seems more sensitive to me at this point, so I went ahead and implemented it in cpan-audit.

**Comment by briandfoy** [comment]
There are other solutions, but I've closed this issue and let's move on.
