### ISSUE TITLE
How to update entries?

### ISSUE THREAD

**Issue by reneeb** [briandfoy/cpan-security-advisory#128]
An issue in CPAN.pm was added with commit d6b37158588993a4183b3852cfbd973805d2e438 . The issue now has an CVE entry: https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-31484

Should we change the id in the yaml file?

Should we update issues when Mitre added some references? E.g. the Gitlab::API::v4 entry (CVE-2023-31485) was updated since it was added to this repository. Should we update make_record to recognise entries for a CVE and update the YAML file?

**Comment by briandfoy** [comment]
I say update the ID in the YAML file.

I'd probably use *make_record* to create the new string and then update the file by hand. I wouldn't do anything to try to replace existing records since there can be other edits that we want to preserve. Programming something to figure all that out will likely take more time than just hand edits.

Automation is as big a win here as one might think. Looking at the new references for Gitlab::API::v4, I see most of them are junk thread messages. I tend to read all the links to see which are relevant anyway.

**Comment by briandfoy** [comment]
I've fixed both of the particular issues.
