### ISSUE TITLE
False positive for CVE-2023-47100 on perl v5.36.3

### ISSUE THREAD

**Issue by sjohnston** [briandfoy/cpan-security-advisory#163]
CPAN::Audit is flagging this CVE on my perl v5.36.3 install. However, v5.36.3 is not in the affected range listed in the cpansa file.

```
14:45:37|0s     perl (have 5.036003) has 1 advisory
14:45:37|0s       * CPANSA-perl-2023-47100
14:45:37|0s         In Perl before 5.38.2, S_parse_uniprop_string in regcomp.c can write to unallocated space because a property name associated with a \p{...} regular expression construct is mishandled. The earliest affected version is 5.30.0.
14:45:37|0s     
14:45:37|0s         Affected range: >=5.30.0,<5.36.3
14:45:37|0s                         >=5.38.0,<5.38.2
14:45:37|0s         Fixed range:    >=5.38.2
14:45:37|0s     
14:45:37|0s         CVEs: CVE-2023-47100
14:45:37|0s     
14:45:37|0s         References:
14:45:37|0s         https://github.com/Perl/perl5/commit/ff1f9f59360afeebd6f75ca1502f5c3ebf077da3
14:45:37|0s         https://github.com/Perl/perl5/commit/12c313ce49b36160a7ca2e9b07ad5bd92ee4a010
14:45:37|0s         https://github.com/Perl/perl5/commit/7047915eef37fccd93e7cd985c29fe6be54650b6
14:45:37|0s     
```

**Comment by bleargh45** [comment]
Related ... am seeing other vendors note that CVE-2023-47100 is a duplicate of CVE-2023-47038 ...

* https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2023-47100
* https://ubuntu.com/security/CVE-2023-47100

Based on that, perhaps all we are missing here is matching `affected_versions` and `fixed_versions` entries, which could be carried forwards from CVE-2023-47038.

I **am** able to confirm that if those versions are carried over from CVE-2023-47038 into CVE-2023-47100, that Perl v5.36.3 is no longer noted as being a vulnerable release.

**Comment by briandfoy** [comment]
Can you show me which version of CPAN::Audit you have?

**Comment by briandfoy** [comment]
I think this may be a duplicate of briandfoy/cpan-audit#62, where the default check is for any advisory for a version greater than or equal to the current version. With perl v5.36.3, there is a greater version that is affected, namely v5.38.0 and v5.38.1.

Consider this search, which has no matches because I include the version range with an explicit `==`, which means the default `>=` is not used. This has no output put

    $ perl5.36.3 -Ilib script/cpan-audit dist perl ==5.36.3
    $ echo $?
    0

If I don't explicitly use the `==`, the search is effectively `>=5.36.3`, which is satisfied by v5.38.0 and v5.38.1:

    $ perl5.36.3 -Ilib script/cpan-audit dist perl 5.36.3
    ... the two reports in question
    $ echo $?
    66

The original author did not include `perl` in his concept of tracking reports, so the idea of backported fixes to old releases wasn't part of the design. That there would be multiple islands of affected versions is something that CPAN::Audit has only recently handled. 

Since I think this issue is really about CPAN::Audit and not cpan-security-advisory, this issue should probably be closed since the report that you show appears to have the correct info. I think the release of CPAN::Audit that fixes briandfoy/cpan-audit#62 will fix this. You might use the `--exclude-file` with these reports until that issue is fixed.

As for the two reports that might be duplicates, that could be a separate and unrelated issue.

**Comment by bleargh45** [comment]
I disagree about this being a duplicate of briandfoy/cpan-audit#62, and instead believe that it is simply a CVE in need of an updated list of affected/fixed versions.

The entry for `CVE-2024-47100` shows:
```
affected_versions:
- '>=5.30.0,<5.36.3'
- '>=5.38.0,<5.38.2'

fixed_versions:
- '>=5.38.2'
```

But I believe that we want:

```
`fixed_versions:
- '5.36.3'
- '>=5.38.2'
```

**Comment by briandfoy** [comment]
`fixed_versions` have no bearing on anything. Nothing uses that field to determine advisories. It's all about the `affected_versions`. The problem is that there are affected versions greater than some versions that were changed.
