### ISSUE TITLE
Image latest fixes a buffer overflow

### ISSUE THREAD

**Issue by robrwo** [briandfoy/cpan-security-advisory#167]
See https://metacpan.org/release/TONYC/Imager-1.025/source/Changes

**Comment by stigtsp** [comment]
Can we verify if this has a security impact somehow? If so, it should have a CVE

**Comment by n1vux** [comment]
The delightfully complete bug-report indicates that this was over-running a
buffer in Malloc heap, not a C buffer on the main stackframes, so any RCE
exploitation will be harder than a classic C buffer overrun. (And stomping
the malloc block headers gets detected because in the versions repored it
wasn't totally optimistically optimi[zs]ed. Mac perl even had a checksum,
nice!)

I suppose there might be a FastCGI or similar web-server process somewhere
using this module that could be DDOS'd by uploading this image repeatedly,
crashing each worker. But that hypothetical DDOS isn't a great basis for a
CVE without a demonstration or actual impact?

**Comment by robrwo** [comment]
I don't think it's a hypothetical security impact. An image file causes it to crash, hence the bug report. Potential for Denial of Service, even if RCEs are difficult. So I think it's better to issue an advisory. I would rather err on the safe side.

**Comment by briandfoy** [comment]
Added report in fa9491e88cd704179e93aa1adc14efd3e569f3b5 . For the CVE, you'll have to talk to the [CPAN Security Group](https://security.metacpan.org).

**Comment by stigtsp** [comment]
CVE has been requested

**Comment by stigtsp** [comment]
This is CVE-2024-53901

**Comment by tonycoz** [comment]
Where do you allocate CVEs from? The  last time I requested one from mitre it took four weeks to get it.
