### ISSUE TITLE
CGI-Application-Plugin-CAPTCHA

### ISSUE THREAD

**Issue by robrwo** [briandfoy/cpan-security-advisory#173]
CGI-Application-Plugin-CAPTCHA v0.01 according to the [Changes](https://metacpan.org/release/CROMEDOME/CGI-Application-Plugin-CAPTCHA-0.04/changes) for v0.02
>         Plugged ugly security hole (thanks, Cees!)

This may be the same issue in https://rt.cpan.org/Ticket/Display.html?id=30759

The diff appears to show that a secret is required for signing the cookie https://metacpan.org/release/CROMEDOME/CGI-Application-Plugin-CAPTCHA-0.02/diff/CROMEDOME/CGI-Application-Plugin-CAPTCHA-0.01

**Comment by stigtsp** [comment]
After a very quick peek:

Looks like it was using DES via `crypt` to protect session secrets as well, this is very likely a problem. 

If there is a default secret, or a low entropy one, it will also be problematic.

```diff
-    my $hash = crypt($random_string, $salt);
+    my $hash = Digest::SHA1::sha1_base64(join("\0", $secret, $random_string));
```

Also, if I understand the implementation correctly, this should probably have been HMAC instead of a custom SHA type contruction.
