### ISSUE TITLE
Need to research CryptX libtomcrypt dependencies

### ISSUE THREAD

**Issue by robrwo** [briandfoy/cpan-security-advisory#24]
CryptX uses [libromcrypt](https://github.com/libtom/libtomcrypt)

The [Changes file](https://metacpan.org/dist/CryptX/changes) notes when the library has been updated, but refers to commits instead of version numbers.

There are a few [CVEs for the library](https://www.cvedetails.com/product/36162/Libtom-Libtomcrypt.html?vendor_id=16188) so it might be worth investigating to see if any versions of CryptX are affected by it.

**Comment by briandfoy** [comment]
There are five CVEs for libtomcrypt:

## CVE-2019-17362	

* In LibTomCrypt through 1.18.2, the der_decode_utf8_string function (in der_decode_utf8_string.c) does not properly detect certain invalid UTF-8 sequences. This allows context-dependent attackers to cause a denial of service (out-of-bounds read and crash) or read information from other memory locations via carefully crafted DER-encoded data.
* Fixed in PR 507

## CVE-2018-12437	

*LibTomCrypt through 1.18.1 allows a memory-cache side-channel attack on ECDSA 
signatures, aka the Return Of the Hidden Number Problem or ROHNP. To discover an ECDSA key, the attacker needs access to either the local machine or a different virtual machine on the same physical host.
* https://github.com/libtom/libtomcrypt/issues/407

## CVE-2017-1000412	

* Linaro's open source TEE solution called OP-TEE, version 2.4.0 (and older) is vulnerable to the bellcore attack in the LibTomCrypt code resulting in compromised private RSA key.

## CVE-2016-6129	

* The rsa_verify_hash_ex function in rsa_verify_hash.c in LibTomCrypt, as used in OP-TEE before 2.2.0, does not validate that the message length is equal to the ASN.1 encoded data length, which makes it easier for remote attackers to forge RSA signatures or public certificates by leveraging a Bleichenbacher signature forgery attack.
* https://github.com/libtom/libtomcrypt/commit/5eb9743410ce4657e9d54fef26a2ee31a1b5dd0
	
## CVE-2016-10335	

* In all Android releases from CAF using the Linux kernel, libtomcrypt was updated.

**Comment by briandfoy** [comment]
This leaves two things to investigate. These led to dead links:

- [ ] CVE-2017-1000412
- [ ] CVE-2016-10335
