### ISSUE TITLE
PDL-IO-Matlab vulnerabilities

### ISSUE THREAD

**Issue by robrwo** [briandfoy/cpan-security-advisory#47]
It uses matio 1.5.0 which has at least one vulnerability, see https://cve.mitre.org/cgi-bin/cvekey.cgi?keyword=matio

**Comment by briandfoy** [comment]
Maybe instead of issues we should come up with a single file/master list of things to investigate. What is easier for you, since you are doing most of the work?

Also, what are you doing to find these? Do they come out of personal work or things that matter in $dayjob, or something else?

This makes me things I need to revitalize MyCPAN and start scanning all of BackPAN again. I did have ways to search for anything I wanted to check. Looking for particular files (say, like the readline issue) would be a good use.

**Comment by robrwo** [comment]
I'm doing this work in my spare time. But it's getting a bit larger than I expected, so I think we need to take a breather and come up with a plan to tackle issues.

I was also hoping that more people would step up and help out.

The issue about zlib #36 mentions how possible distributions were identified.

**Comment by zmughal** [comment]
*PDL

CC: @mohawk2

It seems I should get on with writing that Alien-matio dist I've been meaning to.

**Comment by briandfoy** [comment]
I've [moved this to the wiki](https://github.com/briandfoy/cpan-security-advisory/wiki/External-libraries-to-investigate). Let's reserve issues for things that we can fix and use the wiki for the To Do list.
