### ISSUE TITLE
Investigate HTTP::Parser::XS and Gazelle using picohttpparser

### ISSUE THREAD

**Issue by robrwo** [briandfoy/cpan-security-advisory#95]
These use older versions of [picohttpparser](https://github.com/h2o/picohttpparser) from 2014-2015.  That library has been updated more recently, including changes that might fix buffer overruns

**Comment by briandfoy** [comment]
I couldn't find any advisories for this, and looking through the commit history of picohttpparser, nothing notable was apparent.

If you've found something, can you note it in a comment?

If there's nothing actionable, I suggest moving this to the wiki. I'd like to keep the issues list to things that we can fix  rather than keeping it as a to do list.
